config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  # twitter auth
  get 'twitter_auth', to: redirect('/auth/twitter'), as: 'twitter_auth'
  get '/auth/twitter/callback', to: 'user#twitter_auth'
  match "/auth/failure", to: 'user#failure',  via: [:get, :post]

  # logout
  delete 'logout', to: 'user#logout'

  # public event
  get 'events', to: 'public_event#index', as: 'public_event'
  get 'event/:id', to: 'public_event#show', as: 'show_public_event'

  # dashboard
  get 'dashboard', to: 'events#index'

  # resources
  scope '/dashboard' do
    resources :events do
      resources :tickets
      resources :locations
    end
  end

  # post to twitter
  post 'post_to_twitter/:id', to: 'events#post_to_twitter', as: 'post_to_twitter'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_authorization
  layout "dashboard"

  def index
  end
	
  def require_authorization
		redirect_to root_path unless logged_in?
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_main_menu.html.erb
<aside class="menu">
  <p class="menu-label">
    Loket
  </p>
  <ul class="menu-list">
    <li>
      <a href="<%= root_url %>">Home</a>
    </li>
  </ul>
  <p class="menu-label">
    General
  </p>
  <ul class="menu-list">
    <li>
      <a href="<%= dashboard_url %>">Events</a>
      <ul>
        <li><a class="has-text-grey-light" href="<%= new_event_url %>">Add new Event</a></li>
      </ul>
    </li>
    <p class="menu-label">
      User
    </p>
    <ul class="menu-list">
      <li>
        <%= link_to "Logout".html_safe, logout_path, method: :delete %>
      </li>
    </ul>
  </ul>
</aside>

app/views/dashboard/index.html.erb
# Dashboard