config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  # twitter auth
  get 'twitter_auth', to: redirect('/auth/twitter'), as: 'twitter_auth'
  get '/auth/twitter/callback', to: 'user#twitter_auth'
  match "/auth/failure", to: 'user#failure',  via: [:get, :post]

  # logout
  delete 'logout', to: 'user#logout'

  # public event
  get 'events', to: 'public_event#index', as: 'public_event'
  get 'event/:id', to: 'public_event#show', as: 'show_public_event'

  # dashboard
  get 'dashboard', to: 'events#index'

  # resources
  scope '/dashboard' do
    resources :events do
      resources :tickets
      resources :locations
    end
  end

  # post to twitter
  post 'post_to_twitter/:id', to: 'events#post_to_twitter', as: 'post_to_twitter'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% provide(:title, "With Twitter Auth") %>
<% provide(:description, "Event Management with Twitter Auth") %>
<div id="wrapper">
  <div class="container home-container">
    <h2 class="title has-text-centered">Welcome to Event Management</h2>
    <div class="buttons has-addons is-centered">
      <% if logged_in? %>
        <a href="<%= dashboard_url %>" class="button is-info">
          <span class="icon">
            <i class="fa fa-bullhorn"></i>
          </span>
          <span>Go to Event Management</span>
        </a>
      <% else %>
        <a href="<%= twitter_auth_url %>" class="button is-info">
          <span class="icon">
            <i class="fa fa-twitter"></i>
          </span>
          <span>Login to Create an Event</span>
        </a>
      <% end %>
      <span class="button" disabled>or</span>
      <a class="button is-dark" href="<%= public_event_url %>">See all Events</a>
    </div>
  </div>
</div>