config/routes.rb
Rails.application.routes.draw do
  
  root 'home#index'

  # twitter auth
  get 'twitter_auth', to: redirect('/auth/twitter'), as: 'twitter_auth'
  get '/auth/twitter/callback', to: 'user#twitter_auth'
  match "/auth/failure", to: 'user#failure',  via: [:get, :post]

  # logout
  delete 'logout', to: 'user#logout'

  # public event
  get 'events', to: 'public_event#index', as: 'public_event'
  get 'event/:id', to: 'public_event#show', as: 'show_public_event'

  # dashboard
  get 'dashboard', to: 'events#index'

  # resources
  scope '/dashboard' do
    resources :events do
      resources :tickets
      resources :locations
    end
  end

  # post to twitter
  post 'post_to_twitter/:id', to: 'events#post_to_twitter', as: 'post_to_twitter'

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_one :event_location, dependent: :nullify
  has_many :tickets, dependent: :delete_all

  validates :name, :event_detail, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :require_authorization
  layout "dashboard"

  # Return all events where user_id is current user id
  # Used in views/events/index.html.erb
  def index
    @event = Event.where("user_id = ?", current_user.id)
  end

  # Return Event class to build a form_for
  # Used in views/events/new.html.erb
  def new
    @event = Event.new
  end

  # Create event action to save event parameters
  # It will redirect to event_path(event_id) when successfull
  # and fallback render form if failed
  def create
    @event_params = event_params
    @start_date = @event_params.select {|k, _| k.include? "event_start_date"}.values.join('-').to_date
		@event = current_user.events.create(
      name: @event_params[:name],
      event_detail: @event_params[:event_detail],
      event_start_date: @start_date,
    )
		if @event.save
      redirect_to event_path(@event.id), :flash => { :success => "Your event has been succesfully created" }
		else
			render 'new'
		end
  end
  
  # Show detail on event detail
  # Three different variable to specify location, tickets, and event itself
  def show
    @event = current_user.events.find(params[:id])
    @event_location = @event.event_location
    @event_tickets = @event.tickets
  end

  # Edit event
  # Used in views/events/edit.html.erb
  def edit
    @event = current_user.events.find(params[:id])
  end

  # Update action for edit event form
  # Redirect to event page itself when successfully edit
  # and fallback render edit form when failed
  def update
    @event_params = event_params
    @start_date = @event_params.select {|k, _| k.include? "event_start_date"}.values.join('-').to_date
    @event = current_user.events.find(params[:id]).update_attributes(
      name: @event_params[:name],
      event_detail: @event_params[:event_detail],
      event_start_date: @start_date,
    )
    if @event
      redirect_to event_path(params[:id]), :flash => { :success => "Your event has been edited" }
    else
      render 'edit'
    end
  end

  # Destroy event action
  # Used on events dashboard and show event dashboard (detail event in dashboard)
  def destroy
    @delete = current_user.events.find(params[:id]).destroy
    if @delete
      redirect_to dashboard_path
    else
      redirect_to dashboard_path
    end
  end

  # Post to twitter
  # Uses a method helper in helpers/twitter_helper.rb called event_post_to_twitter
  def post_to_twitter
    tweet = event_post_to_twitter(current_user.events.find(params[:id]))
    if tweet
      tweet_url = "https://twitter.com/#{current_user.twitter_username}/status/#{tweet.id}"
      redirect_to request.referer,
        :flash => { :success => "Your event has been twitted,
                    <br><i class='fa fa-twitter'></i> 
                    <a href='#{tweet_url}' rel='nofollow' target='_blank'>#{tweet_url}</a>" }
    else
      redirect_to request.referer, :flash => { :error => "Ooops. something wrong" }
    end
  end

  # Private method include event_params
  # Used by create action and edit action
	private
		def event_params
			params.require(:event).permit(:name, :event_detail, :event_start_date, :event_end_date)
		end

	def require_authorization
		redirect_to root_path unless logged_in?
	end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_breadcrumb_all.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="<%= dashboard_url %>">Events</a></li>
    <li class="is-active"><a href="#" aria-current="page"><%= breadcrumb_var %></a></li>
  </ul>
</nav>

app/views/events/_breadcrumb_form.html.erb
<nav class="breadcrumb" aria-label="breadcrumbs">
  <ul>
    <li><a href="<%= dashboard_url %>">Events</a></li>
    <li><a href="<%= event_url(breadcrumb_var_id) %>">
        <%= breadcrumb_var %></a>
    </li>
    <li class="is-active"><a href="#" aria-current="page"><%= breadcrumb_var_current %></a></li>
  </ul>
</nav>

app/views/events/edit.html.erb
<%= render "/events/breadcrumb_form", breadcrumb_var: @event.name, breadcrumb_var_id: @event.id, breadcrumb_var_current: "Edit" %>

<h2 class="title">Edit Event</h2>
<%= form_for @event, url: {action: "update"} do |f| %>
  <div class="field">
    <label class="label">Event Name</label>
    <div class="control has-icons-left">
      <%= f.text_field :name, class: "input" %>
      <span class="icon is-small is-left">
        <i class="fa fa-bullhorn"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <label class="label">Event Details</label>
    <div class="control">
      <%= f.text_area :event_detail, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <label class="label">Event Start Date</label>
      <div class="control">
        <div class="select">
          <div class="field is-grouped">
          <%= f.date_select :event_start_date,
            {
              :start_year => 2018, 
              :end_year => 2020
            },
            selected: @event.event_start_date.to_date,
            default: @event.event_start_date.to_date
          %>
          </div>
        </div>
      </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <input type="submit" class="button is-link" value="Save"/>
    </div>
  </div>
<% end %>

app/views/events/index.html.erb
<%= render "/shared/flash" %>
<h2 class="title">Your Events</h2>
<div id="event_content">
  <% if @event.count >= 1 %>
    <% @event.each do |e| %>
      <div class="columns">
        <div class="column is-8">
          <a class="is-size-6" href="<%= event_url(e.id) %>"><%= e.name %></a>
        </div>
        <div class="column">
          <a href="<%= edit_event_url(e.id) %>" class="button is-small is-dark">Edit</a>
          <a title="Post to Twitter" href="<%= post_to_twitter_url(e.id) %>" data-method="post" class="button is-small is-info">
            <i class="fa fa-twitter"></i>
          </a>
          <a href="<%= event_url(e.id) %>" data-method="delete" class="button is-small is-danger">Delete</a>
        </div>
      </div>
      <hr/>
    <% end %>
  <% else %>
    You haven't create an Event.<br/>
    <a href="<%= new_event_url %>" class="button is-info">Create Event</a>
  <% end %>
</div>

app/views/events/new.html.erb
<%= render "/events/breadcrumb_all", breadcrumb_var: "Add new event" %>

<h2 class="title">Add new Event</h2>
<%= form_for @event, url: {action: "create"} do |f| %>
  <div class="field">
    <label class="label">Event Name</label>
    <div class="control has-icons-left">
      <%= f.text_field :name, class: "input" %>
      <span class="icon is-small is-left">
        <i class="fa fa-bullhorn"></i>
      </span>
    </div>
  </div>

  <div class="field">
    <label class="label">Event Details</label>
    <div class="control">
      <%= f.text_area :event_detail, class: "textarea" %>
    </div>
  </div>

  <div class="field">
    <label class="label">Event Start Date</label>
      <div class="control">
        <div class="select">
          <div class="field is-grouped">
          <%= f.date_select :event_start_date,
            {
              :start_year => 2018, 
              :end_year => 2020
            }
          %>
          </div>
        </div>
      </div>
  </div>

  <div class="field is-grouped">
    <div class="control">
      <input type="submit" class="button is-link" value="Create Event"/>
    </div>
  </div>
<% end %>

app/views/events/show.html.erb
<%= render "/shared/flash" %>
<%= render "/events/breadcrumb_all", breadcrumb_var: @event.name %>
<div class="content">
  <h1 class="is-size-3 has-text-weight-light">
    <%= @event.name %>
  </h1>
  <p>
    <a href="<%= edit_event_url(@event.id) %>" class="button is-small">Edit Event</a>
    <a title="Delete this event?" href="<%= event_url(@event.id) %>" data-method="delete" class="button is-small is-danger">
      <i class="fa fa-trash"></i>
    </a>
    <a title="Post to Twitter" href="<%= post_to_twitter_url(@event.id) %>" data-method="post" class="button is-small is-info">
      <i class="fa fa-twitter"></i>
    </a>
    <a title="See on event page" href="<%= show_public_event_path(@event.id) %>" class="button is-small is-warning">
      <i class="fa fa-eye"></i>
    </a>
  </p>
  <p class="has-text-grey">
    <i class="fa fa-calendar"></i> <%= Date.parse(@event.event_start_date.to_s).strftime("%A, %d %B %Y") %> <br>
    <% if !@event.event_location.nil? %>
      <i class="fa fa-map"></i> <%= @event.event_location.location.name %>
      <a href="<%= edit_event_location_url(@event.id, @event.event_location.location.id) %>" class="button is-small">Edit Location</a>
      <a href="<%= event_location_url(@event.id, @event.event_location.location.id) %>" data-method="delete" class="button is-small is-danger" title="delete location"><i class="fa fa-trash"></i></a><br>
      <%= @event.event_location.description %>
    <% else %>
      <i class="fa fa-map"></i> <a href="<%= new_event_location_url(@event.id) %>" class="button is-small">Set Location</a>
    <% end %>
  </p>
  <blockquote>
    <%= @event.event_detail %>
  </blockquote>
  
  <hr/>
  <p class="has-text-grey">
    Tickets
  </p>
  <% if @event_tickets.count >= 1 %>
    <% @event_tickets.each do |t| %>
      <div class="box">
        <div class="content">
          <p>
            <strong><%= t.ticket_name %></strong> <small><%= t.ticket_price %></small>
            <br>
            <%= t.ticket_detail %>
            <br>
            <a href="<%= edit_event_ticket_url(@event.id, t.id) %>" class="button is-small">
              <span class="icon">
                <i class="fa fa-edit"></i>
              </span>
            </a>
            <a class="button is-danger is-small" data-method="delete" href="<%= event_ticket_url(@event.id, t.id) %>">
              <span class="icon">
                <i class="fa fa-trash"></i>
              </span>
            </a>
          </p>
        </div>
      </div>
    <% end %>
      <a href="<%= new_event_ticket_url(@event.id) %>" class="button">Add More Ticket</a>
  <% else %>
    <div class="box">
      <a href="<%= new_event_ticket_url(@event.id) %>" class="button">Add Ticket</a>
    </div>
  <% end %>
</div>